name: Todo Android Build

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI and jq
        run: |
          npm install --global eas-cli
          sudo apt-get update && sudo apt-get install -y jq curl

      - name: Build Android app with EAS (wait for completion)
        run: |
          eas build --platform android --profile production --non-interactive --json --wait > build.json
          BUILD_URL=$(jq -r '.[0].artifacts.buildUrl' build.json)
          echo "Build URL: $BUILD_URL"
          curl -L $BUILD_URL -o app.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Expo Android Build ${{ github.run_number }}"
          files: app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
